services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      cache_from:
        - ${CONTAINER_NAME}:latest
    image: ${CONTAINER_NAME}
    restart: always
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - app_net
      - proxy_net

networks:
  app_net: # 4. Статический ключ
    name: ${APP_NETWORK} # 5. Динамическое ИМЯ из переменной
    external: true
  proxy_net: # 6. Статический ключ
    name: ${NGINX_NETWORK} # 7. Динамическое ИМЯ из переменной
    external: true