services:
  logoped_frontend:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      cache_from:
        - logoped_frontend:latest
    image: logoped_frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../../.env.production
